---
- name: "WORKER | CHECKS | Install check apt dependencies"
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - curl
    - dnsutils
    - freetds-dev
    - ldap-utils
    - locales
    - medusa

- name: "WORKER | CHECKS | Import Microsoft Repo Key"
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: "WORKER | CHECKS | Register Microsoft Repository"
  shell: curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list

- name: "WORKER | CHECKS | Install mssql-tools"
  apt:
    name: "{{ item }}"
    update_cache: yes
  environment:
    ACCEPT_EULA: Y
  with_items:
    - mssql-tools
    - unixodbc-dev

- name: "WORKER | CHECKS | Register Locales"
  shell: echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen

- name: "WORKER | CHECKS | Generate Locales"
  shell: locale-gen

- name: "WORKER | CHECKS | Install check pip dependencies"
  shell: /home/engine/scoring_engine/env/bin/pip3.5 install {{ item }}
  with_items:
    - paramiko
    - pysmb
    - requests

- name: "WORKER | CHECKS | Install custom smtp check"
  copy:
    src: /home/engine/scoring_engine/src/scoring_engine/engine/checks/bin/smtp_check
    dest: /usr/bin/smtp_check
    remote_src: true

- name: "WORKER | CHECKS | Install custom smtps check"
  copy:
    src: /home/engine/scoring_engine/src/scoring_engine/engine/checks/bin/smtps_check
    dest: /usr/bin/smtps_check
    remote_src: true

- name: "WORKER | CHECKS | Set smtp_check executable"
  file:
    path: /usr/bin/smtp_check
    mode: "u+x,g-x,o-x"

- name: "WORKER | CHECKS | Set smtps_check executable"
  file:
    path: /usr/bin/smtps_check
    mode: "u+x,g-x,o-x"
