---
language: python
python:
  - "3.6"
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install dependences
  - pip install ansible ansible-lint

script:
  - ansible-lint tasks/main.yml

  # Check the role/playbook's syntax.
  - ansible-playbook --syntax-check --list-tasks tests/test.yml --sudo

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook --connection=local -vvvv tests/test.yml --sudo  -e 'ansible_python_interpreter=/usr/bin/python3'

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - netstat -paunt
  - ps aux | grep python

  # Request a page via the web server, to make sure it's running and responds.
  - "curl http://localhost/"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
