---
- include: debian/setup.yml
  when: ansible_distribution == "Debian"

- include: ubuntu/setup.yml
  when: ansible_distribution == "Ubuntu"

# Web
- include: web/mysql.yml
- include: web/nginx.yml
- include: web/service.yml

# Engine
- include: engine/redis.yml
- include: engine/service.yml

# Worker
- include: worker/service.yml
- include: worker/checks.yml
